[project]
name = "fcc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.1",
    "mysqlclient>=2.2.7",
    "numpy>=2.4.1",
    "render>=1.0.0",
]
